#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Michael Skrynski"
email = "zlorfi@gmail.com"

[ui]
# pager = "delta"
# diff-editor = "nvim"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
